name: GaitMixer
channels:
  - metric-learning
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cryptography=38.0.1
  - cuda=11.6.2
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=11.8.86
  - cuda-libraries=11.6.2
  - cuda-libraries-dev=11.6.2
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=11.8.87
  - cuda-runtime=11.6.2
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.6.2
  - cuda-tools=11.6.2
  - cuda-visual-tools=11.6.2
  - docker-pycreds=0.4.0
  - einops=0.4.1
  - ffmpeg=4.3
  - fftw=3.3.9
  - freetype=2.12.1
  - gds-tools=1.4.0.31
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.29
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - nsight-compute=2022.3.0.22
  - numexpr=2.8.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.3
  - pathtools=0.1.2
  - pillow=9.2.0
  - pip=22.2.2
  - promise=2.3
  - protobuf=3.20.1
  - psutil=5.9.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - pytorch-metric-learning=1.6.2
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.1
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - sentry-sdk=1.10.1
  - setproctitle=1.2.2
  - setuptools=63.4.1
  - shortuuid=1.0.9
  - six=1.16.0
  - smmap=3.0.5
  - sqlite=3.39.3
  - threadpoolctl=2.2.0
  - timm=0.4.12
  - tk=8.6.12
  - torchvision=0.14.0
  - tqdm=4.64.1
  - typing_extensions=4.3.0
  - tzdata=2022e
  - urllib3=1.26.12
  - wandb=0.13.4
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
